// file: CardsOntology.java generated by ontology bean generator.  DO NOT EDIT, UNLESS YOU ARE REALLY SURE WHAT YOU ARE DOING!
package proj1.ontology;

import jade.content.onto.*;
import jade.content.schema.*;

/** file: CardsOntology.java
 * @author ontology bean generator
 * @version 2026/04/22, 17:37:03
 */
public class CardsOntology extends jade.content.onto.Ontology  {

  private static final long serialVersionUID = 7810243947702126400L;

  //NAME
  public static final String ONTOLOGY_NAME = "cards";
  // The singleton instance of this ontology
  private static Ontology theInstance = new CardsOntology();
  public static Ontology getInstance() {
     return theInstance;
  }


   // VOCABULARY
    public static final String CARDSDEALT_CARDS="cards";
    public static final String CARDSDEALT="CardsDealt";
    public static final String ISWINNER_PLAYER="player";
    public static final String ISWINNER_PRIZE="prize";
    public static final String ISWINNER="IsWinner";
    public static final String PLAYMOVE_PLAYEDCARD="playedCard";
    public static final String PLAYMOVE="PlayMove";
    public static final String SUBSCRIBETOGAME_GAMENAME1="gameName1";
    public static final String SUBSCRIBETOGAME="SubscribeToGame";
    public static final String REQUESTRULES_GAMENAME="gamename";
    public static final String REQUESTRULES="RequestRules";
    public static final String GAMESTATE_ISGAMEOVER="isGameOver";
    public static final String GAMESTATE_CURRENTTURN="currentTurn";
    public static final String GAMESTATE="GameState";
    public static final String PLAYER_BALANCE="balance";
    public static final String PLAYER_NAME="Name";
    public static final String PLAYER="Player";
    public static final String GAMEINFO_MINPLAYERS="minPlayers";
    public static final String GAMEINFO_GAMENAME="gameName";
    public static final String GAMEINFO_DESCRIPTION="description";
    public static final String GAMEINFO="GameInfo";
    public static final String CARD_VALUE="value";
    public static final String CARD_RANK="rank";
    public static final String CARD_SUIT="suit";
    public static final String CARD="Card";

  /**
   * Constructor
  */
  private CardsOntology(){ 
    super(ONTOLOGY_NAME, BasicOntology.getInstance());
    try { 

    // adding Concept(s)
    ConceptSchema cardSchema = new ConceptSchema(CARD);
    add(cardSchema, proj1.ontology.Card.class);
    ConceptSchema gameInfoSchema = new ConceptSchema(GAMEINFO);
    add(gameInfoSchema, proj1.ontology.GameInfo.class);
    ConceptSchema playerSchema = new ConceptSchema(PLAYER);
    add(playerSchema, proj1.ontology.Player.class);
    ConceptSchema gameStateSchema = new ConceptSchema(GAMESTATE);
    add(gameStateSchema, proj1.ontology.GameState.class);

    // adding AgentAction(s)
    AgentActionSchema requestRulesSchema = new AgentActionSchema(REQUESTRULES);
    add(requestRulesSchema, proj1.ontology.RequestRules.class);
    AgentActionSchema subscribeToGameSchema = new AgentActionSchema(SUBSCRIBETOGAME);
    add(subscribeToGameSchema, SubscribeToGame.class);
    AgentActionSchema playMoveSchema = new AgentActionSchema(PLAYMOVE);
    add(playMoveSchema, proj1.ontology.PlayMove.class);

    // adding AID(s)

    // adding Predicate(s)
    PredicateSchema isWinnerSchema = new PredicateSchema(ISWINNER);
    add(isWinnerSchema, proj1.ontology.IsWinner.class);
    PredicateSchema cardsDealtSchema = new PredicateSchema(CARDSDEALT);
    add(cardsDealtSchema, proj1.ontology.CardsDealt.class);


    // adding fields
    cardSchema.add(CARD_SUIT, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    cardSchema.add(CARD_RANK, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    cardSchema.add(CARD_VALUE, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    gameInfoSchema.add(GAMEINFO_DESCRIPTION, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    gameInfoSchema.add(GAMEINFO_GAMENAME, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    gameInfoSchema.add(GAMEINFO_MINPLAYERS, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    playerSchema.add(PLAYER_NAME, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    playerSchema.add(PLAYER_BALANCE, (TermSchema)getSchema(BasicOntology.FLOAT), ObjectSchema.MANDATORY);
    gameStateSchema.add(GAMESTATE_CURRENTTURN, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    gameStateSchema.add(GAMESTATE_ISGAMEOVER, (TermSchema)getSchema(BasicOntology.BOOLEAN), ObjectSchema.MANDATORY);
    requestRulesSchema.add(REQUESTRULES_GAMENAME, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    subscribeToGameSchema.add(SUBSCRIBETOGAME_GAMENAME1, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.OPTIONAL);
    playMoveSchema.add(PLAYMOVE_PLAYEDCARD, cardSchema, ObjectSchema.OPTIONAL);
    isWinnerSchema.add(ISWINNER_PRIZE, (TermSchema)getSchema(BasicOntology.FLOAT), ObjectSchema.MANDATORY);
    isWinnerSchema.add(ISWINNER_PLAYER, playerSchema, ObjectSchema.MANDATORY);
    cardsDealtSchema.add(CARDSDEALT_CARDS, cardSchema, 1, ObjectSchema.UNLIMITED);

    // adding name mappings

    // adding inheritance

   }catch (java.lang.Exception e) {e.printStackTrace();}
  }
}
